changed library versions

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -37,10 +37,11 @@ jobs:
         run: |
           dvc remote list  # List current remotes for verification
 
-      # Step 6: Pull the latest data version using DVC
-     # - name: DVC Pull latest data
-     #   run: |
-      #    dvc pull -v || (echo "DVC pull failed. Ensure the data is available in the DVC remote." && exit 1)
+      Step 6: Pull the latest data version using DVC
+     - name: DVC Pull latest data
+       run: |
+         dvc pull 
+        #-v || (echo "DVC pull failed. Ensure the data is available in the DVC remote." && exit 1)
 
       # Step 7: Run the training script
       - name: Run training script
