changed library versions

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -3,7 +3,7 @@ name: Retrain Model on DVC Data Changes
 on:
   push:
     branches:
-      - main
+      - main  # Trigger on pushes to the 'main' branch
 
 jobs:
   retrain:
@@ -35,13 +35,12 @@ jobs:
       # Step 5: Check DVC remote configuration
       - name: Check DVC remote configuration
         run: |
-          dvc remote list  # List current remotes for verification
+          dvc remote list  # Verifies that the remotes are properly configured
 
-      Step 6: Pull the latest data version using DVC
-     - name: DVC Pull latest data
-       run: |
-         dvc pull 
-      #-v || (echo "DVC pull failed. Ensure the data is available in the DVC remote." && exit 1)
+      # Step 6: DVC Pull latest data with debug
+      - name: DVC Pull latest data
+        run: |
+          dvc pull -v --jobs 1 || (echo "DVC pull failed. Ensure the data is available in the DVC remote." && exit 1)
 
       # Step 7: Run the training script
       - name: Run training script
